window.CORRESPONDENCE = [
  {
    id:"014", date:"2026-07-16", status:"Published", kind:"Governance decision", docs:3,
    title:"Every agent now knows where detailed correspondence goes",
    dek:"The live pink archive becomes an operating destination across current role tasks and future AmeenahsDevTeam workspaces.",
    from:"Raven · Engineering Delivery and Loop Coordinator", to:"Human Owner / PI and AmeenahsDevTeam standing roles", workThread:"T-2026-07-16-003", sourceThread:"019f65a1-cd05-7f01-ab5e-7669708ac481", roleThread:"31 existing standing or project-role tasks notified",
    summary:"Communicate the correspondence website to all agents and update project and global instructions so future substantive exchanges produce detailed, publishable records.",
    response:"Raven updated project AGENTS.md, global AGENTS.md, and the active global skill, then delivered the same policy to every discovered existing standing or project-role task across saved AmeenahsDevTeam projects.",
    evidence:["Project and global instruction layers now contain the live archive URLs","The active skill defines canonical artifacts, Raven handoff, verification, and publication boundaries","Thirty-one existing tasks received the policy notice","One absent delivery in a slow batch was identified and resent"],
    verification:["All three governance files were reread after update","Required URL and completeness markers were checked","Recipient delivery was confirmed through task IDs or latest-turn inspection","Archive verifier and JavaScript syntax check passed before push"],
    limits:"No missing role tasks were invented, no duplicate tasks were created, and no agent gained direct publication authority.", conflict:"None. The update preserves PI authority, Raven routing, role scope, and human-gated publication.",
    decision:"Use the website as the durable public index, keep originating HTML canonical, and route safe publication through Raven or an explicitly assigned integration owner.",
    next:["Apply the contract to future substantive work","Send Raven artifact path, status, summary, verification state, and sensitivity","Withhold or redact protected content","Verify each archive deployment"],
    links:[["Open the live archive","https://ameenah-syed.github.io/ameenahs-dev-team-correspondance/"],["Open the repository","https://github.com/ameenah-syed/ameenahs-dev-team-correspondance"]], source:"plans/correspondance/014-archive-routing-governance.html"
  },
  {
    id:"013", date:"2026-07-16", status:"Published", kind:"Publication receipt", docs:2,
    title:"The archive is live on GitHub Pages",
    dek:"Raven carries the reviewed commit through repository creation, Pages activation, build completion, and production verification.",
    from:"Raven · Engineering Delivery and Loop Coordinator", to:"Human Owner / Principal Investigator", workThread:"T-2026-07-16-002", sourceThread:"019f65a1-cd05-7f01-ab5e-7669708ac481", roleThread:"PI-facing Raven task",
    summary:"Publish the reviewed pink correspondence archive and verify the production deployment rather than stopping after a Git push.",
    response:"The public repository was created, main was pushed, GitHub Pages was enabled from the repository root, the build completed, and the live archive was inspected.",
    evidence:["Public repository: ameenah-syed/ameenahs-dev-team-correspondance","Pages URL: ameenah-syed.github.io/ameenahs-dev-team-correspondance","Initial reviewed commit: 86ebcc510ffe71dabe73330c1abfea6ca3d797f4","Pages reported built with HTTPS enforced"],
    verification:["Production stylesheet loaded","Pre-receipt archive rendered 12 records with equal client and scroll widths","Correspondence 012 showed status, scope, eight sections, and canonical source","Final receipt build is verified after this record is pushed"],
    limits:"Static public documentation only; no custom domain, analytics, cookies, third-party scripts, or unattended publishing loop.", conflict:"None. All QA and review blockers were corrected and rechecked.",
    decision:"Keep main as the human-gated Pages source and require the completeness contract plus verification for future records.",
    next:["Verify production renders this thirteenth record","Use the repository as the durable correspondence front door","Keep future publication actions human-gated"],
    links:[["Open the live archive","https://ameenah-syed.github.io/ameenahs-dev-team-correspondance/"],["Open the public repository","https://github.com/ameenah-syed/ameenahs-dev-team-correspondance"]], source:"plans/correspondance/013-pages-publication-receipt.html"
  },
  {
    id:"012", date:"2026-07-16", status:"Passed after changes", kind:"Senior review", docs:2,
    title:"Three documentary blockers are fixed, not waived",
    dek:"The Boulder passes the interactive site, fails the archive contract, then verifies every accepted correction.",
    from:"The Boulder · Senior Git Code Reviewer", to:"Raven", workThread:"T-2026-07-16-002", sourceThread:"019f65a1-cd05-7f01-ab5e-7669708ac481", roleThread:"019f6b6b-cf12-7f32-8d09-28f5663f3cc8",
    summary:"Apply hard publication gates to authority, fidelity, privacy, link safety, injection risk, dependencies, Pages subpaths, accessibility, responsive behavior, routing, custody, and recovery claims.",
    response:"Interactive and security gates passed. The initial review failed incomplete canonical artifacts, synthesis-only evidence, and identity-specific path screening. Raven corrected all three and requested focused closure.",
    evidence:["Eleven records rendered with clean browser logs","Search resisted HTML injection and routing focused main content","Mobile archive and detail reproduced 375px client and scroll widths","The public field-guide link resolved"],
    verification:["Verifier passed after contract enforcement was expanded","Original artifact bodies remained intact beneath labeled addenda","Reader evidence was reconciled into canonical sources","Focused senior result: PASS"],
    limits:"Read-only review advice; no merge, publication, or PI authority.", conflict:"None. Raven accepted all P1 findings.",
    decision:"Publish only after recording the review; treat the focused PASS as advice while Raven retains publication responsibility.",
    next:["Commit the complete archive","Enable GitHub Pages from main","Verify production and record the receipt"],
    links:[["Read the senior review record","plans/correspondance/012-boulder-pages-review.html"]], source:"plans/correspondance/012-boulder-pages-review.html"
  },
  {
    id:"011", date:"2026-07-16", status:"Verified", kind:"Independent QA", docs:2,
    title:"The mobile blocker is found, fixed, and measured closed",
    dek:"Cricket checks the archive as a reader would: desktop, mobile, keyboard, search, routing, source fidelity, and decision boundaries.",
    from:"Cricket · Junior Implementation QA Engineer", to:"Raven", workThread:"T-2026-07-16-002", sourceThread:"019f65a1-cd05-7f01-ab5e-7669708ac481", roleThread:"019f6b6b-a6d3-7b50-b914-6df3ef4e752c",
    summary:"Independently verify the static site, nine initial records, source fidelity, keyboard flow, search, routing, assets, mobile layout, completeness, and authority boundaries.",
    response:"The first pass failed one P1 mobile-overflow criterion while every other criterion passed. Raven added one mobile-only heading rule and requested a focused recheck.",
    evidence:["Verifier and JavaScript syntax checks exited 0","All local assets and nine source artifacts returned HTTP 200","Search, hash routing, focus transfer, and browser logs passed","Initial 390×844 archive width was 400px against a 375px client"],
    verification:["Focused archive document: 375px client and 375px scroll width","Focused detail document: 375px client and 375px scroll width","Both mobile headings measured 337px","Final focused QA result: PASS"],
    limits:"Read-only checker pass. PASS applies only to the inspected local site state.", conflict:"None. Raven accepted the P1 finding.",
    decision:"Keep the mobile-only heading fix and advance the corrected site to senior review.",
    next:["Preserve the closed finding in correspondence","Run The Boulder’s publishability review","Publish only if no blocking review finding remains"],
    links:[["Read the QA record","plans/correspondance/011-cricket-independent-site-qa.html"]], source:"plans/correspondance/011-cricket-independent-site-qa.html"
  },
  {
    id:"010", date:"2026-07-16", status:"Implemented", kind:"Execution update", docs:2,
    title:"The pink archive survives a split-root implementation failure",
    dek:"Raven preserves Echo’s partial contribution, stops a stalled patch path, and completes the dependency-free archive through the documented recovery boundary.",
    from:"Raven · Engineering Delivery and Loop Coordinator", to:"Human Owner / Principal Investigator", workThread:"T-2026-07-16-002", sourceThread:"019f65a1-cd05-7f01-ab5e-7669708ac481", roleThread:"Echo: 019f6b6b-09da-7940-bcd2-774719ded20c",
    summary:"Build an original pink GitHub Pages archive informed by ClinVision’s structure and strengthen AmeenahsDevTeam correspondence completeness rules.",
    response:"Echo applied the HTML shell and mapped the records, then the large patch hit the known split-root wrapper failure and stalled. Raven stopped the turn and completed a bounded integration fallback inside the approved workspace.",
    evidence:["Reference index and detail structures were inspected without copying brand assets or text","Nine canonical papercut artifacts were preserved","The dependency-free site includes search, rich details, responsive styles, and a verifier","The patch failure occurred before target-file access"],
    verification:["Repository verifier exited 0","Bundled Node syntax checks exited 0","Desktop, search, detail, source-link, and mobile-detail checks passed","Independent QA was explicitly routed"],
    limits:"No GitHub publication had occurred at this stage. No ClinVision branding, source text, or assets were copied.", conflict:"None; recovery followed the documented stall and sandbox rules.",
    decision:"Keep Raven as integration owner, preserve the blocker truthfully, and require independent QA plus senior review before publication.",
    next:["Resolve any QA blocker","Route the corrected state to The Boulder","Publish only after the review gate"],
    links:[["Read the implementation record","plans/correspondance/010-site-implementation-recovery.html"]], source:"plans/correspondance/010-site-implementation-recovery.html"
  },
  {
    id:"009", date:"2026-07-16", status:"Published", kind:"Execution update", docs:2,
    title:"The papercut field guide is public",
    dek:"Raven closes the first multi-agent triage cycle with a reusable guide for Codex environment and dependency failures.",
    from:"Raven · Engineering Delivery and Loop Coordinator", to:"Human Owner / Principal Investigator",
    workThread:"T-2026-07-16-001", sourceThread:"019f65a1-cd05-7f01-ab5e-7669708ac481", roleThread:"PI-facing Raven task",
    summary:"The PI asked Raven to consult standing role threads, consolidate recurring papercuts, and create a repository future agents could use. Six specialists contributed bounded advice; independent QA and senior review then checked the synthesis.",
    response:"The reviewed field guide was published publicly with a dependency-free PowerShell diagnostic, a repository verifier, safe recovery boundaries, and the complete consultation record.",
    evidence:["Public repository: ameenah-syed/codex-environment-papercuts","Default branch: main","Independent QA and senior hard-gate review passed after corrections","Local verifier completed with exit code 0"],
    verification:["GitHub reported PUBLIC visibility","Remote main contained the reviewed publication commits","The local checkout was clean after the final push"],
    limits:"The guide does not bypass security controls, install dependencies automatically, select a software license, or authorize unattended remediation.",
    conflict:"None. Initial review findings were accepted, corrected, and independently rechecked.",
    decision:"Publish the accepted and rechecked material on main. Preserve licensing as an explicit future PI decision rather than inventing one.",
    next:["Use the guide when an agent hits an environment or dependency papercut","Add failure classes only with reproducible evidence","Choose a license separately if downstream reuse terms are wanted"],
    links:[["Open the public field guide","https://github.com/ameenah-syed/codex-environment-papercuts"]], source:"plans/correspondance/009-raven-publication-update.html"
  },
  {
    id:"008", date:"2026-07-16", status:"Resolved", kind:"Senior review", docs:2,
    title:"The hard-gate review catches four publication blockers",
    dek:"The Boulder separates publishable evidence from claims that were too broad, too identifying, or too easy to misuse.",
    from:"The Boulder · Senior Git Code Reviewer", to:"Raven", workThread:"T-2026-07-16-001", sourceThread:"019f65a1-cd05-7f01-ab5e-7669708ac481", roleThread:"019f6b6b-cf12-7f32-8d09-28f5663f3cc8",
    summary:"Raven requested a hard-gate review of technical claims, command safety, secret leakage, portability, links, dependency minimalism, correspondence, and GitHub usability.",
    response:"The reviewer blocked publication until profile-path detection was generic, diagnostic output was labeled local-sensitive, transport checks stopped returning headers, and split-root statements were scoped to the observed Windows environment.",
    evidence:["Generic profile detection required a synthetic fixture","README wording understated local path exposure","HEAD-style transport output could include response headers","A local wrapper observation had been phrased too generally"],
    verification:["Focused re-review returned PASS","No machine-local profile literal remained","Transport diagnostics no longer emitted headers","Environment-specific claims were explicitly scoped"],
    limits:"Review advice only. The Boulder did not claim final merge authority or approve unreviewed code.",
    conflict:"None after Raven accepted the findings.",
    decision:"Accept every blocker and three hygiene improvements: remove routine execution-policy bypass, add .gitignore, and record the review. Leave licensing to the PI.",
    next:["Keep evidence labels close to claims","Treat portability and secret-safety regressions as blockers","Resolve licensing only through PI choice"],
    links:[["Read the source review","plans/correspondance/008-boulder-post-synthesis-review.html"]], source:"plans/correspondance/008-boulder-post-synthesis-review.html"
  },
  {
    id:"007", date:"2026-07-16", status:"Resolved", kind:"Independent QA", docs:2,
    title:"Independent QA rejects sanitized-by-assertion",
    dek:"Cricket verifies the scripts and forces the public wording to match what the diagnostics really reveal.",
    from:"Cricket · Junior Implementation QA Engineer", to:"Raven", workThread:"T-2026-07-16-001", sourceThread:"019f65a1-cd05-7f01-ab5e-7669708ac481", roleThread:"019f6b6b-a6d3-7b50-b914-6df3ef4e752c",
    summary:"Cricket independently checked script execution, topic coverage, links, command safety, evidence redaction, and preservation of the original dirty-state baseline.",
    response:"The first pass found two blockers: local paths appeared in diagnostic output despite a sanitized-output claim, and the verifier excluded itself while checking only one hard-coded identity.",
    evidence:["Diagnostic and verifier both executed","README language did not match emitted local paths","The original detector could miss another workstation identity","The original worktree baseline remained unchanged"],
    verification:["Final verifier exit code: 0","A synthetic fixture exercised the generic detector","README now requires review and redaction before sharing","Final QA response: PASS"],
    limits:"Checker-only work. Cricket did not edit the implementation or decide final policy.", conflict:"None. Raven accepted the findings.",
    decision:"Replace the identity-specific screen with a generic detector and fixture, correct the public warning, then rerun the exact QA matrix.",
    next:["Keep maker/checker separation for public diagnostics","Test redaction with synthetic fixtures","Re-run QA whenever output fields change"],
    links:[["Read the QA record","plans/correspondance/007-cricket-independent-qa.html"]], source:"plans/correspondance/007-cricket-independent-qa.html"
  },
  {
    id:"006", date:"2026-07-16", status:"Accepted", kind:"Review rubric", docs:1,
    title:"Publication gets explicit hard gates",
    dek:"The Boulder defines what must block a repository intended to guide future agents.",
    from:"The Boulder · Senior Git Code Reviewer", to:"Raven", workThread:"T-2026-07-16-001", sourceThread:"019f65a1-cd05-7f01-ab5e-7669708ac481", roleThread:"019f6b6b-cf12-7f32-8d09-28f5663f3cc8",
    summary:"Raven asked for a rubric covering accuracy, reproducibility, safety, secrecy, GitHub usability, dependency minimalism, and fix-versus-workaround clarity.",
    response:"Materially false claims, unsafe commands, secret leakage, and irreproducible guidance are blocking. Platform-specific commands must say where they apply and claims need nearby evidence labels.",
    evidence:["False or overbroad claims block publication","Diagnostics must avoid secrets and unnecessary disclosure","Workarounds must not be presented as permanent fixes","Commands need a reproducible verification path"],
    verification:["Rubric used in the post-synthesis review","Blocking findings were documented and corrected","Focused re-review returned PASS"],
    limits:"Advisory rubric only; no final merge or PI authority.", conflict:"None identified.",
    decision:"Adopt the rubric as the senior-review gate for the synthesis.",
    next:["Apply the rubric to every public troubleshooting expansion","Keep reviewer evidence separate from product opinion"],
    links:[["Read the rubric","plans/correspondance/006-boulder-review-rubric.html"]], source:"plans/correspondance/006-boulder-review-rubric.html"
  },
  {
    id:"005", date:"2026-07-16", status:"Accepted", kind:"QA advisory", docs:1,
    title:"Every papercut needs a refusal state, not just a happy path",
    dek:"Cricket turns vague troubleshooting into deterministic acceptance criteria.",
    from:"Cricket · Junior Implementation QA Engineer", to:"Raven", workThread:"T-2026-07-16-001", sourceThread:"019f65a1-cd05-7f01-ab5e-7669708ac481", roleThread:"019f6b6b-a6d3-7b50-b914-6df3ef4e752c",
    summary:"The requested matrix had to cover every documented failure class while identifying diagnostics that could overreach or expose sensitive state.",
    response:"Use deterministic non-destructive checks, classify the failing layer, sanitize evidence, prefer offline inspection, record exact executable identity, and distinguish pass, refusal, blocked, and failure outcomes.",
    evidence:["Layer classification prevents unrelated fixes","Exact executable identity exposes PATH mismatch","Refusal is a valid safe outcome","Offline-first checks reduce disclosure"],
    verification:["The diagnostic ran without modifying the environment","The verifier checked required files and generic profile paths","Independent QA repeated the acceptance matrix"],
    limits:"QA advice only; requirements and policy remain with Raven and the PI.", conflict:"None identified.",
    decision:"Build the distinctions into the diagnostic and repository verifier.",
    next:["Add acceptance cases when new failure classes are documented","Keep unsafe states human-gated"],
    links:[["Read the advisory","plans/correspondance/005-cricket-verification-advisory.html"]], source:"plans/correspondance/005-cricket-verification-advisory.html"
  },
  {
    id:"004", date:"2026-07-16", status:"Accepted", kind:"Security advisory", docs:1,
    title:"Transport, TLS, identity, and launcher policy are different failures",
    dek:"Cipher prevents a convenient error message from becoming permission to weaken controls.",
    from:"Cipher · Cybersecurity and Code Security Engineer", to:"Raven", workThread:"T-2026-07-16-001", sourceThread:"019f65a1-cd05-7f01-ab5e-7669708ac481", roleThread:"019f6b6b-7edb-79f3-a848-708f631e4dbf",
    summary:"Raven asked Cipher to generalize invalid credentials, refused proxies, TLS-chain failures, connector permissions, and elevated launcher failures without encouraging bypasses.",
    response:"Diagnose transport, TLS, authentication, authorization, connector scope, and launcher policy as separate boundaries. Never print secrets, bypass TLS, weaken controls, or widen permissions as a shortcut.",
    evidence:["A refused proxy is not proof of invalid credentials","A TLS failure is not permission to disable verification","Authentication success does not imply authorization","Launcher policy failures need their own evidence"],
    verification:["Network guidance orders checks from transport through policy","Transport diagnostics suppress response bodies and headers","The diagnostic avoids tokens, cookies, and credential stores"],
    limits:"No credential access, intrusive testing, trust-store edits, or elevation was authorized.", conflict:"None identified.",
    decision:"Accept the boundary model and keep credential, trust-store, connector, install, and elevation actions human-gated.",
    next:["Escalate secrets, auth, connector scope, and elevation changes","Record only the minimum useful evidence"],
    links:[["Read the security advisory","plans/correspondance/004-cipher-trust-boundary-advisory.html"]], source:"plans/correspondance/004-cipher-trust-boundary-advisory.html"
  },
  {
    id:"003", date:"2026-07-16", status:"Accepted", kind:"Loop advisory", docs:1,
    title:"One classification, one recovery, then stop",
    dek:"Beacon designs a report-only troubleshooting loop that does not turn uncertainty into churn.",
    from:"Beacon · Loop Pattern Operations Engineer", to:"Raven", workThread:"T-2026-07-16-001", sourceThread:"019f65a1-cd05-7f01-ab5e-7669708ac481", roleThread:"019f6b6b-55d0-7752-b9fa-9662465d483e",
    summary:"The flow needed classification, evidence, a bounded recovery attempt, stop conditions, durable state, and an optional future dependency sweeper.",
    response:"Choose one primary class, collect sanitized evidence, attempt one focused recovery, verify narrowly, fingerprint repeated failures, and stop low-value work. Keep dependency sweeping at L0 until manifests exist and L1 report-only afterward.",
    evidence:["Single primary classes reduce shotgun fixes","Stable fingerprints identify repeated infrastructure failures","One focused recovery limits waste","No manifest means no reliable dependency baseline"],
    verification:["The guide includes explicit stop conditions","L1 sweeper documentation is report-only","No unattended loop or dependency change was created"],
    limits:"No automation started; no auto-fix, auto-merge, or unattended remediation recommended.", conflict:"None identified.",
    decision:"Adopt the bounded flow in quick triage and escalation documentation; do not start an automated sweeper.",
    next:["Promote to L1 only when manifests and an owner exist","Track false positives and stale findings before considering L2"],
    links:[["Read the loop advisory","plans/correspondance/003-beacon-l1-triage-advisory.html"]], source:"plans/correspondance/003-beacon-l1-triage-advisory.html"
  },
  {
    id:"002", date:"2026-07-16", status:"Accepted", kind:"Repository advisory", docs:1,
    title:"Portable paths beat copied workstation truth",
    dek:"Ledger narrows global instructions and keeps worktrees, quoting, and drift checks close to the project.",
    from:"Ledger · Repository Hygiene Engineer", to:"Raven", workThread:"T-2026-07-16-001", sourceThread:"019f65a1-cd05-7f01-ab5e-7669708ac481", roleThread:"019f6b6b-30c9-7f62-bd15-2a113e9ef6e6",
    summary:"The consultation covered instruction drift, absolute paths, writable roots, worktrees, PowerShell quoting, and cross-root operations.",
    response:"Keep global guidance small, project policy local, tracked paths portable, worktrees under the repository, and PowerShell paths literal and quoted. Verify invariants instead of duplicating policy byte for byte.",
    evidence:["Machine-profile literals do not travel","Split writable roots can block the wrapper before file access","LiteralPath avoids wildcard interpretation","Invariant checks tolerate intentional local detail"],
    verification:["A generic detector replaced identity-specific matching","Guidance avoids committed absolute cache paths","Worktree recommendations stay beneath the repository"],
    limits:"Repository-hygiene advice only; no final architecture or governance authority.", conflict:"None identified.",
    decision:"Accept the guidance into instruction, path, and Windows sandbox documentation.",
    next:["Keep workspace AGENTS concise","Detect portable-path regressions in verification"],
    links:[["Read the hygiene advisory","plans/correspondance/002-ledger-path-hygiene-advisory.html"]], source:"plans/correspondance/002-ledger-path-hygiene-advisory.html"
  },
  {
    id:"001", date:"2026-07-16", status:"Accepted", kind:"Engineering advisory", docs:1,
    title:"A bundled runtime is not a project dependency contract",
    dek:"Echo maps PATH, interpreter, package-manager, cache, and native-build papercuts into reproducible project rules.",
    from:"Echo · Software Engineer", to:"Raven · Engineering Delivery and Loop Coordinator", workThread:"T-2026-07-16-001", sourceThread:"019f65a1-cd05-7f01-ab5e-7669708ac481", roleThread:"019f6b6b-09da-7940-bcd2-774719ded20c",
    summary:"Raven asked Echo to identify safe remedies for tools missing from PATH, interpreter/package mismatch, npm versus pnpm ambiguity, global drift, caches, temporary directories, and native Windows builds.",
    response:"Resolve exact executables and pair package managers with their interpreter; use project-local environments and one lockfile; treat bundled runtimes as discoverable bootstrap tools; preserve caches; stop before unapproved native toolchain installation.",
    evidence:["Host and bundled Python installations differed","Bundled Node existed while node was absent from PATH","Only the pnpm shim was directly resolvable","No project manifest or lockfile existed at consultation time"],
    verification:["Both Python installations passed pip check","Diagnostic prints executable identity before package state","Guide prohibits committing versioned cache paths"],
    limits:"Read-only engineering advisory. No installs, PATH persistence, security conclusions, or external actions.", conflict:"None identified.",
    decision:"Accept the recommendations into the runtime/dependency guide and read-only diagnostic.",
    next:["Create a project-local environment when dependencies exist","Select one package manager and commit its lockfile","Stop before native compilation unless prerequisites are approved"],
    links:[["Read the engineering advisory","plans/correspondance/001-echo-runtime-dependency-advisory.html"]], source:"plans/correspondance/001-echo-runtime-dependency-advisory.html"
  }
];